name: Run Docker Container
#on: [push]

jobs:
  run-container:
    runs-on: ubuntu-latest

    steps:
    #- uses: actions/checkout@v2
    #
    #- name: Set up Docker
    #  run: |
    #    sudo apt-get update
    #    sudo apt-get install -y docker.io

    - name: Run Docker Container
      run: |
        docker pull my-docker-image:latest
        docker run my-docker-image:latest /path/to/my-script.sh
		
